name: my_flutter_web_chat_app
description: FLUTTER WEB CHAT APP

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4

  # api calling
  http: ^0.13.4

  # MMVM architecture
  stacked: ^2.3.6

  # state management
  get: ^4.6.3
  rxdart: ^0.27.3

  build_runner: ^2.1.11

  # firebase
  firebase_core: ^1.17.0
  firebase_messaging: ^11.4.0
  firebase_storage: ^10.2.16
  cloud_firestore: ^3.1.15
  firebase_auth: ^3.3.18

  # local push notification
  flutter_local_notifications: ^9.5.3+1

  # screen & app util
  flutter_screenutil: ^5.5.3+1
  intl: ^0.17.0

  # image & doc picker
  image_picker: ^0.8.5+3
  file_picker: ^4.5.1
  photo_manager: ^2.1.1
  media_picker: ^1.3.5
  flutter_absolute_path: ^1.0.6

  # path prover
  path_provider: ^2.0.10

  # permission handler
  permission_handler: 9.2.0

  # open file from chat
  open_file: ^3.2.1

  # download and cache image
  cached_network_image: ^3.2.1

  # generate http link and launch
  flutter_linkify: ^5.0.2
  url_launcher: ^6.1.2

  # chat pagination
  paginate_firestore: ^1.0.3+1


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/font/Nunito-Bold.ttf
        - asset: assets/font/Nunito-ExtraBold.ttf
          weight: 900
        - asset: assets/font/Nunito-Regular.ttf
        - asset: assets/font/Nunito-SemiBold.ttf
          weight: 500